CREATE TABLE board(
NO NUMBER(8) CONSTRAINT board_no_pk PRIMARY KEY,
title VARCHAR2(100),
writer VARCHAR2(45),
CONTENT VARCHAR2(400),
hit NUMBER(5),
groupno NUMBER(3),
regdate date);
CREATE SEQUENCE board_seq
INCREMENT BY 1
START WITH 1;